### ISSUE TITLE
[![Auto Review Bot](https://github.com/ethereum/ERCs/actions/workflows/auto-review-bot.yml/badge.svg?branch=master&event=workflow_run)](https://github.com/ethereum/ERCs/actions/workflows/auto-review-bot.yml)

### ISSUE THREAD

**Issue by Vantu432** [unifiedjs/awesome-unified#1]
[![Auto Review Bot](https://github.com/ethereum/ERCs/actions/workflows/auto-review-bot.yml/badge.svg?branch=master&event=workflow_run)](https://github.com/ethereum/ERCs/actions/workflows/auto-review-bot.yml)

_Originally posted by @Vantu432 in https://github.com/unifiedjs/collective/issues/34#issuecomment-1954907818_

**Comment by ChristianMurphy** [comment]
Please stop spamming issues
